const crypto = require('crypto');
const { v4: uuidv4 } = require('uuid');
const deviceRepository = require('../repositories/device.repository');
const attendanceEventRepository = require('../repositories/attendanceEvent.repository');
const schoolSessionRepository = require('../repositories/schoolSession.repository');
const studentRepository = require('../repositories/student.repository');
const { NotFoundError, ConflictError, BadRequestError } = require('../utils/appError');

/**
 * The device api_key is the only credential a gate tablet ever holds. Anything
 * that knows it can post attendance for that gate, so it is treated the way a
 * password hash is treated: generated by the server, never accepted from a
 * client, and never returned by a route whose purpose is something else.
 */
function generateApiKey() {
  return `dev_${crypto.randomBytes(24).toString('hex')}`;
}

/**
 * Strip the credential before a device leaves the service.
 *
 * findById selects api_key because pairing genuinely needs it; every other
 * caller does not. Removing it here rather than at each call site means a new
 * endpoint added later leaks nothing by default — the unsafe path has to be
 * written on purpose.
 */
function withoutApiKey(device) {
  if (!device) return device;
  const { api_key, ...aman } = device;
  return aman;
}

class DeviceService {
  async getAll(query) {
    const { status, type, search, page = 1, limit = 20 } = query;
    const offset = (page - 1) * limit;

    const [items, total] = await Promise.all([
      deviceRepository.findAll({ status, type, search, limit, offset }),
      deviceRepository.countAll({ status, type, search })
    ]);

    return {
      items,
      pagination: {
        page: parseInt(page, 10),
        limit: parseInt(limit, 10),
        total,
        totalPages: Math.ceil(total / limit)
      }
    };
  }

  async getById(id) {
    return withoutApiKey(await this.getByIdWithSecret(id));
  }

  /**
   * Internal lookup that keeps the credential. Only the two key routes below
   * are allowed to call it; everything else goes through getById.
   */
  async getByIdWithSecret(id) {
    const item = await deviceRepository.findById(id);
    if (!item) {
      throw new NotFoundError(`Attendance device with ID ${id} not found`);
    }
    return item;
  }

  async create(data) {
    const existingCode = await deviceRepository.findByCode(data.code);
    if (existingCode) {
      throw new ConflictError(`Device with code '${data.code}' already exists`);
    }

    // uuid and api_key are assigned here and NEVER taken from the request.
    // Both used to fall through from the body: `data.api_key || generated`
    // accepted whatever a caller sent, which let the gate credential be set to
    // a weak or already-known value and made the server's random generation
    // decorative. The request cannot name its own identifiers.
    const { api_key: _abaikanKunci, uuid: _abaikanUuid, ...bersih } = data;

    const id = await deviceRepository.create({
      ...bersih,
      uuid: uuidv4(),
      api_key: generateApiKey()
    });

    return this.getById(id);
  }

  async update(id, data) {
    const existing = await this.getById(id);

    if (data.code && data.code !== existing.code) {
      const duplicate = await deviceRepository.findByCode(data.code);
      if (duplicate && duplicate.id !== parseInt(id, 10)) {
        throw new ConflictError(`Device with code '${data.code}' already exists`);
      }
    }

    // Same reasoning as create: identity and credential are not editable
    // through the ordinary update route. Rotating the key has its own method
    // below, so that replacing a gate credential is always a deliberate act
    // and never a side effect of renaming a gate.
    const { api_key: _abaikanKunci, uuid: _abaikanUuid, ...bersih } = data;

    await deviceRepository.update(id, bersih);
    return this.getById(id);
  }

  /**
   * Reveal the credential so a tablet can be paired to this gate.
   *
   * Deliberately its own POST route rather than a field on GET /devices/:id.
   * The listing and detail screens an administrator opens every day now carry
   * no secret at all, and the one call that does carry it says so in its name
   * — which is what makes it auditable, and what keeps it out of caches, error
   * reports and browser devtools of pages that had no business holding it.
   */
  async revealKey(id) {
    const device = await this.getByIdWithSecret(id);
    if (device.status !== 'active') {
      throw new BadRequestError(
        'This gate is not active, so pairing a tablet to it would produce a device that cannot scan'
      );
    }
    return { id: device.id, code: device.code, name: device.name, api_key: device.api_key };
  }

  /**
   * Replace the credential. This is the revocation mechanism.
   *
   * A tablet that is lost or stolen keeps working forever otherwise: it holds
   * the key, the key never expires, and nothing else identifies it. Rotating
   * is the only way to take that away — and it necessarily unpairs every
   * tablet on this gate, which is exactly the point and must be said plainly
   * in the interface.
   */
  async rotateKey(id) {
    const device = await this.getByIdWithSecret(id);
    const api_key = generateApiKey();
    await deviceRepository.update(id, { api_key });
    return { id: device.id, code: device.code, name: device.name, api_key };
  }

  async delete(id) {
    const device = await this.getById(id);

    /**
     * A gate that has recorded attendance is never deleted.
     *
     * Every foreign key to attendance_devices is ON DELETE SET NULL, so the
     * attendance rows survive — but the record of WHICH GATE a child was
     * scanned at is erased for the whole history, silently and with no way
     * back. That is evidence, and a school that is asked months later where a
     * student entered has nothing to answer with. Deactivating stops the
     * device from scanning and keeps the history intact.
     */
    const terpakai = await attendanceEventRepository.countAll({ device_id: id });
    if (terpakai > 0) {
      throw new ConflictError(
        `Gate '${device.code}' has ${terpakai} attendance events recorded against it. ` +
          'Set its status to inactive instead; deleting it would erase which gate those scans happened at.'
      );
    }

    await deviceRepository.delete(id);
    return true;
  }

  /**
   * Everything a gate tablet needs to run on its own, keyed by the device
   * credential instead of a member of staff.
   *
   * The tablet used to assemble this from /school-sessions/active and
   * /students, both of which require a user token — so a device screwed to a
   * corridor wall had to keep a staff session alive indefinitely just to
   * refresh its student list, and whoever picked the tablet up held that
   * account. A gate already proves who it is with its own key; it should never
   * have needed a person's.
   *
   * The payload is deliberately the minimum that lets a card be recognised at
   * the gate: no addresses, no phone numbers, no guardians. A tablet in a
   * public corridor is the last place a full student record belongs.
   */
  async bootstrap(device) {
    const [session, students] = await Promise.all([
      schoolSessionRepository.findActive(),
      studentRepository.findAll({ status: 'active', limit: 5000, offset: 0 })
    ]);

    return {
      device: { id: device.id, code: device.code, name: device.name },
      session: session || null,
      students: (students || []).map((s) => ({
        id: s.id,
        nis: s.nis,
        name: s.name,
        class_name: s.class_name,
        photo: s.photo || null
      })),
      server_time: new Date().toISOString()
    };
  }

  async ping(id) {
    await this.getByIdWithSecret(id);
    await deviceRepository.updateLastSeen(id);
    return { id, last_seen_at: new Date() };
  }
}

module.exports = new DeviceService();
